/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SmartCANJaguar* RobotMap::drivetrainFrontLeft = NULL;
SmartCANJaguar* RobotMap::drivetrainFrontRight = NULL;
SmartCANJaguar* RobotMap::drivetrainBackLeft = NULL;
SmartCANJaguar* RobotMap::drivetrainBackRight = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	drivetrainFrontLeft = new SmartCANJaguar(2);
	
	
	drivetrainFrontRight = new SmartCANJaguar(5);
	
	
	drivetrainBackLeft = new SmartCANJaguar(3);
	
	
	drivetrainBackRight = new SmartCANJaguar(4);
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	
}
